package com.regnosys.rosetta.generator.python.func;

import com.google.inject.Inject;
import com.regnosys.rosetta.generator.python.PythonCodeGenerator;
import com.regnosys.rosetta.rosetta.RosettaModel;
import com.regnosys.rosetta.tests.RosettaInjectorProvider;
import com.regnosys.rosetta.tests.util.ModelHelper;
import java.util.Collections;
import java.util.HashMap;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

/**
 * Test Principal
 */
@ExtendWith(InjectionExtension.class)
@InjectWith(RosettaInjectorProvider.class)
@SuppressWarnings("all")
public class PythonFunctionsTest {
  @Inject
  @Extension
  private ModelHelper _modelHelper;

  @Inject
  private PythonCodeGenerator generator;

  @Test
  public void testSimpleSet() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func Abs: <\"Returns the absolute value of a number. If the argument is not negative, the argument is returned. If the argument is negative, the negation of the argument is returned.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("arg number (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("result number (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set result:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if arg < 0 then -1 * arg else arg");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def Abs(arg: Decimal) -> Decimal:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns the absolute value of a number. If the argument is not negative, the argument is returned. If the argument is negative, the negation of the argument is returned.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("arg : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("result : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn0():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return (-1 * rosetta_resolve_attr(self, \"arg\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn0():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return rosetta_resolve_attr(self, \"arg\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("result =  if_cond_fn(all_elements(rosetta_resolve_attr(self, \"arg\"), \"<\", 0), _then_fn0, _else_fn0)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return result");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testSimpleAdd() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func AppendToVector: <\"Append a single value to a vector (list of numbers).\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("vector number (0..*) <\"Input vector.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("value number (1..1) <\"Value to add to the vector.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("resultVector number (0..*) <\"Resulting vector.\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("add resultVector: vector");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("add resultVector: value");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def AppendToVector(vector: list[Decimal] | None, value: Decimal) -> Decimal:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Append a single value to a vector (list of numbers).");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("vector : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Input vector.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("value : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Value to add to the vector.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("resultVector : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("resultVector = rosetta_resolve_attr(self, \"vector\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("resultVector.add_rosetta_attr(self, rosetta_resolve_attr(self, \"value\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return resultVector");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testSetWithBasemodel() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func Create_UnitType: <\"Create UnitType with given currency or financial unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("currency string (0..1)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("[metadata scheme]");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("financialUnit FinancialUnitEnum (0..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("unitType UnitType (1..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("condition CurrencyOrFinancialUnitExists:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("currency exists or financialUnit exists");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set unitType -> currency: currency");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set unitType -> financialUnit: financialUnit");
    _builder.newLine();
    _builder.append("enum FinancialUnitEnum: <\"Provides enumerated values for financial units, generally used in the context of defining quantities for securities.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Contract <\"Denotes financial contracts, such as listed futures and options.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ContractualProduct <\"Denotes a Contractual Product as defined in the CDM.  This unit type would be used when the price applies to the whole product, for example, in the case of a premium expressed as a cash amount.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("IndexUnit <\"Denotes a price expressed in index points, e.g. for a stock index.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("LogNormalVolatility <\"Denotes a log normal volatility, expressed in %/month, where the percentage is represented as a decimal. For example, 0.15 means a log-normal volatility of 15% per month.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Share <\"Denotes the number of units of financial stock shares.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ValuePerDay <\"Denotes a value (expressed in currency units) for a one day change in a valuation date, which is typically used for expressing sensitivity to the passage of time, also known as theta risk, or carry, or other names.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ValuePerPercent <\"Denotes a value (expressed in currency units) per percent change in the underlying rate which is typically used for expressing sensitivity to volatility changes, also known as vega risk.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Weight <\"Denotes a quantity (expressed as a decimal value) represented the weight of a component in a basket.\">");
    _builder.newLine();
    _builder.append("type UnitType: <\"Defines the unit to be used for price, quantity, or other purposes\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("capacityUnit CapacityUnitEnum (0..1) <\"Provides an enumerated value for a capacity unit, generally used in the context of defining quantities for commodities.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("weatherUnit WeatherUnitEnum (0..1) <\"Provides an enumerated values for a weather unit, generally used in the context of defining quantities for commodities.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("financialUnit FinancialUnitEnum (0..1) <\"Provides an enumerated value for financial units, generally used in the context of defining quantities for securities.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("currency string (0..1) <\"Defines the currency to be used as a unit for a price, quantity, or other purpose.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("[metadata scheme]");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("condition UnitType: <\"Requires that a unit type must be set.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("one-of");
    _builder.newLine();
    _builder.append("enum CapacityUnitEnum: <\"Provides enumerated values for capacity units, generally used in the context of defining quantities for commodities.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ALW <\"Denotes Allowances as standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("BBL <\"Denotes a Barrel as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("BCF <\"Denotes Billion Cubic Feet as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("BDFT <\"Denotes Board Feet as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("CBM <\"Denotes Cubic Meters as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("CER <\"Denotes Certified Emissions Reduction as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("CRT <\"Denotes Climate Reserve Tonnes as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("DAG <\"Denotes 10 grams as a standard unit used in precious metals contracts (e.g MCX).\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("DAY <\"Denotes a single day as a standard unit used in time charter trades.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("DMTU <\"Denotes Dry Metric Ton (Tonne) Units - Consists of a metric ton of mass excluding moisture.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ENVCRD <\"Denotes Environmental Credit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ENVOFST <\"Denotes Environmental Offset as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("FEU <\"Denotes a 40 ft. Equivalent Unit container as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("G <\"Denotes a Gram as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBBSH <\"Denotes a GB Bushel as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBBTU <\"Denotes a GB British Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBCWT <\"Denotes a GB Hundredweight unit as standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBGAL <\"Denotes a GB Gallon unit as standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBMBTU <\"Denotes a Thousand GB British Thermal Units as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBMMBTU <\"Denotes a Million GB British Thermal Units as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBT <\"Denotes a GB Ton as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GBTHM <\"Denotes a GB Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GJ <\"Denotes a Gigajoule as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GW <\"Denotes a Gigawatt as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GWH <\"Denotes a Gigawatt-hour as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("HL <\"Denotes a Hectolitre as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("HOGB <\"Denotes a 100-troy ounces Gold Bar as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ISOBTU <\"Denotes an ISO British Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ISOMBTU <\"Denotes a Thousand ISO British Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ISOMMBTU <\"Denotes a Million ISO British Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("ISOTHM <\"Denotes an ISO Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KG <\"Denotes a Kilogram as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KL <\"Denotes a Kilolitre as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KW <\"Denotes a Kilowatt as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KWD <\"Denotes a Kilowatt-day as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KWH <\"Denotes a Kilowatt-hour as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KWM <\"Denotes a Kilowatt-month as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KWMIN <\"Denotes a Kilowatt-minute as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("KWY <\"Denotes a Kilowatt-year as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("L <\"Denotes a Litre as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("LB <\"Denotes a Pound as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MB <\"Denotes a Thousand Barrels as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MBF <\"Denotes a Thousand board feet, which are used in contracts on forestry underlyers as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MJ <\"Denotes a Megajoule as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MMBF <\"Denotes a Million board feet, which are used in contracts on forestry underlyers as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MMBBL <\"Denotes a Million Barrels as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MSF <\"Denotes a Thousand square feet as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MT <\"Denotes a Metric Ton as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MW <\"Denotes a Megawatt as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MWD <\"Denotes a Megawatt-day as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MWH <\"Denotes a Megawatt-hour as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MWM <\"Denotes a Megawatt-month as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MWMIN <\"Denotes a Megawatt-minute as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MWY <\"Denotes a Megawatt-year as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("OZT <\"Denotes a Troy Ounce as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("SGB <\"Denotes a Standard Gold Bar as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("TEU <\"Denotes a 20 ft. Equivalent Unit container as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("USBSH <\"Denotes a US Bushel as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("USBTU <\"Denotes a US British Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("USCWT <\"Denotes US Hundredweight unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("USGAL <\"Denotes a US Gallon unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("USMBTU <\"Denotes a Thousand US British Thermal Units as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("USMMBTU <\"Denotes a Million US British Thermal Units as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("UST <\"Denotes a US Ton as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("USTHM <\"Denotes a US Thermal Unit as a standard unit.\">");
    _builder.newLine();
    _builder.append("enum WeatherUnitEnum: <\"Provides enumerated values for weather units, generally used in the context of defining quantities for commodities.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("CDD <\"Denotes Cooling Degree Days as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("CPD <\"Denotes Critical Precipitation Day as a standard unit.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("HDD <\"Heating Degree Day as a standard unit.\">");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def Create_UnitType(currency: str | None, financialUnit: FinancialUnitEnum | None) -> UnitType:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Create UnitType with given currency or financial unit.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("currency : string");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("financialUnit : FinancialUnitEnum");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("unitType : UnitType");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("_pre_registry = {}");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("@rosetta_local_condition(_pre_registry)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def condition_0_CurrencyOrFinancialUnitExists(self):");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return (rosetta_attr_exists(rosetta_resolve_attr(self, \"currency\")) or rosetta_attr_exists(rosetta_resolve_attr(self, \"financialUnit\")))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# Execute all registered conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("execute_local_conditions(_pre_registry, \'Pre-condition\')");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("unitType = _get_rosetta_object(\'UnitType\', \'currency\', rosetta_resolve_attr(self, \"currency\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("unitType = set_rosetta_attr(rosetta_resolve_attr(self, \'unitType\'), \'financialUnit\', rosetta_resolve_attr(self, \"financialUnit\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return unitType");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testAddAndSet() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func ResolvePerformanceReset: <\"Defines how to resolve the reset value for a performance payout.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("observation Observation (1..1) <\"Represents the observation that will be used to compute the reset value.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("date date (1..1) <\"Specifies the date of the reset.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("reset Reset (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set reset -> resetValue: <\"Assigns the observed value to the reset value.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("observation -> observedValue");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set reset -> resetDate:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("date");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("add reset -> observations: <\"Assigns the observation required to compute the rest value as audit.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("observation");
    _builder.newLine();
    _builder.append("type Reset: <\"Defines the reset value or fixing value produced in cashflow calculations, during the life-cycle of a financial instrument. The reset process defined in Create_Reset function joins product definition details with observations to compute the reset value.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[metadata key]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("resetValue Price (1..1) <\"Specifies the reset or fixing value. The fixing value could be a cash price, interest rate, or other value.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("resetDate date (1..1) <\"Specifies the date on which the reset occurred.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("observations Observation (1..*)");
    _builder.newLine();
    _builder.append("type Price : ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("price int(1..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("type Observation: <\"Defines a single, numerical value that was observed in the marketplace. Observations of market data are made independently to business events or trade life-cycle events, so data instances of Observation can be created independently of any other model type, hence it is annotated as a root type. Observations will be broadly reused in many situations, so references to Observation are supported via the \'key\' annotation.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[rootType]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[metadata key]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("observedValue Price (1..1) <\"Specifies the observed value as a number.\">");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def ResolvePerformanceReset(observation: Observation, date: datetime.date) -> Reset:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Defines how to resolve the reset value for a performance payout.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("observation : Observation");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Represents the observation that will be used to compute the reset value.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("date : date");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Specifies the date of the reset.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("reset : Reset");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("reset = _get_rosetta_object(\'Reset\', \'resetValue\', rosetta_resolve_attr(rosetta_resolve_attr(self, \"observation\"), \"observedValue\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("reset = set_rosetta_attr(rosetta_resolve_attr(self, \'reset\'), \'resetDate\', rosetta_resolve_attr(self, \"date\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("reset.add_rosetta_attr(rosetta_resolve_attr(rosetta_resolve_attr(self, reset), \'observations\'), rosetta_resolve_attr(self, \"observation\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return reset");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testFilterOperation() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func FilterQuantity: <\"Filter list of quantities based on unit type.\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("quantities Quantity (0..*) <\"List of quantities to filter.\">");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("unit UnitType (1..1) <\"Currency unit type.\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("filteredQuantities Quantity (0..*)");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("add filteredQuantities:");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("quantities");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("filter quantities -> unit = unit");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("type Quantity: <\"Specifies a quantity as a single value to be associated to a financial product, for example a transfer amount resulting from a trade. This data type extends QuantitySchedule and requires that only the single amount value exists.\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("value number (0..1) <\"Specifies the value of the measure as a number. Optional because in a measure vector or schedule, this single value may be omitted.\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("unit UnitType (0..1) <\"Qualifies the unit by which the amount is measured. Optional because a measure may be unit-less (e.g. when representing a ratio between amounts in the same unit).\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("type UnitType: <\"Defines the unit to be used for price, quantity, or other purposes\">");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("value int (1..1)");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def FilterQuantity(quantities: list[Quantity] | None, unit: UnitType) -> Quantity:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Filter list of quantities based on unit type.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("quantities : Quantity");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("List of quantities to filter.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("unit : UnitType");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Currency unit type.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("filteredQuantities : Quantity");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("filteredQuantities = rosetta_filter(rosetta_resolve_attr(self, \"quantities\"), lambda item: all_elements(rosetta_resolve_attr(rosetta_resolve_attr(self, \"quantities\"), \"unit\"), \"=\", rosetta_resolve_attr(self, \"unit\")))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return filteredQuantities");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testWithEnumAttr() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("enum ArithmeticOperationEnum: <\"An arithmetic operator that can be passed to a function\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Add <\"Addition\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Subtract <\"Subtraction\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Multiply <\"Multiplication\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Divide <\"Division\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Max <\"Max of 2 values\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Min <\"Min of 2 values\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("func ArithmeticOperation:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("n1 number (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("op ArithmeticOperationEnum (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("n2 number (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("result number (1..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set result:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if op = ArithmeticOperationEnum -> Add then");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("n1 + n2");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("else if op = ArithmeticOperationEnum -> Subtract then");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("n1 - n2");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("else if op = ArithmeticOperationEnum -> Multiply then");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("n1 * n2");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("else if op = ArithmeticOperationEnum -> Divide then");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("n1 / n2");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("else if op = ArithmeticOperationEnum -> Max then");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Max( n1, n2 )");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("else if op = ArithmeticOperationEnum -> Min then");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Min( n1, n2 )");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def ArithmeticOperation(n1: Decimal, op: ArithmeticOperationEnum, n2: Decimal) -> Decimal:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("n1 : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("op : ArithmeticOperationEnum");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("n2 : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("result : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn5():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return Min(rosetta_resolve_attr(self, \"n1\"), rosetta_resolve_attr(self, \"n2\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn5():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return True");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn4():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return Max(rosetta_resolve_attr(self, \"n1\"), rosetta_resolve_attr(self, \"n2\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn4():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return if_cond_fn(all_elements(rosetta_resolve_attr(self, \"op\"), \"=\", rosetta_resolve_attr(ArithmeticOperationEnum, \"MIN\")), _then_fn5, _else_fn5)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn3():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return (rosetta_resolve_attr(self, \"n1\") / rosetta_resolve_attr(self, \"n2\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn3():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return if_cond_fn(all_elements(rosetta_resolve_attr(self, \"op\"), \"=\", rosetta_resolve_attr(ArithmeticOperationEnum, \"MAX\")), _then_fn4, _else_fn4)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn2():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return (rosetta_resolve_attr(self, \"n1\") * rosetta_resolve_attr(self, \"n2\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn2():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return if_cond_fn(all_elements(rosetta_resolve_attr(self, \"op\"), \"=\", rosetta_resolve_attr(ArithmeticOperationEnum, \"DIVIDE\")), _then_fn3, _else_fn3)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn1():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return (rosetta_resolve_attr(self, \"n1\") - rosetta_resolve_attr(self, \"n2\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn1():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return if_cond_fn(all_elements(rosetta_resolve_attr(self, \"op\"), \"=\", rosetta_resolve_attr(ArithmeticOperationEnum, \"MULTIPLY\")), _then_fn2, _else_fn2)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn0():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return (rosetta_resolve_attr(self, \"n1\") + rosetta_resolve_attr(self, \"n2\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn0():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return if_cond_fn(all_elements(rosetta_resolve_attr(self, \"op\"), \"=\", rosetta_resolve_attr(ArithmeticOperationEnum, \"SUBTRACT\")), _then_fn1, _else_fn1)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("result =  if_cond_fn(all_elements(rosetta_resolve_attr(self, \"op\"), \"=\", rosetta_resolve_attr(ArithmeticOperationEnum, \"ADD\")), _then_fn0, _else_fn0)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return result");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testFilterOperation2() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func FilterQuantityByCurrencyExists: <\"Filter list of quantities based on unit type.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("quantities QuantitySchedule (0..*) <\"List of quantities to filter.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("filteredQuantities QuantitySchedule (0..*)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("add filteredQuantities:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("quantities");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("filter item -> unit -> currency exists");
    _builder.newLine();
    _builder.append("type QuantitySchedule: <\"Specifies a quantity as a single value to be associated to a financial product, for example a transfer amount resulting from a trade. This data type extends QuantitySchedule and requires that only the single amount value exists.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("value number (0..1) <\"Specifies the value of the measure as a number. Optional because in a measure vector or schedule, this single value may be omitted.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("unit UnitType (0..1) <\"Qualifies the unit by which the amount is measured. Optional because a measure may be unit-less (e.g. when representing a ratio between amounts in the same unit).\">");
    _builder.newLine();
    _builder.append("type UnitType: <\"Defines the unit to be used for price, quantity, or other purposes\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("currency string(0..1)");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def FilterQuantityByCurrencyExists(quantities: list[QuantitySchedule] | None) -> QuantitySchedule:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Filter list of quantities based on unit type.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("quantities : QuantitySchedule");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("List of quantities to filter.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("filteredQuantities : QuantitySchedule");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("filteredQuantities = rosetta_filter(rosetta_resolve_attr(self, \"quantities\"), lambda item: rosetta_attr_exists(rosetta_resolve_attr(rosetta_resolve_attr(item, \"unit\"), \"currency\")))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return filteredQuantities");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testAlias1() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func testAlias:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("inp1 number(1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("inp2 number(1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("result number(1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("alias Alias:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if inp1 < 0 then inp1");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set result:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Alias");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def testAlias(inp1: Decimal, inp2: Decimal) -> Decimal:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("inp1 : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("inp2 : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("result : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _then_fn0():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return rosetta_resolve_attr(self, \"inp1\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def _else_fn0():");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return True");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Alias = if_cond_fn(all_elements(rosetta_resolve_attr(self, \"inp1\"), \"<\", 0), _then_fn0, _else_fn0)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("result =  rosetta_resolve_attr(self, \"Alias\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return result");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testAlias2() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("type A:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("valueA number(1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("type B:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("valueB number(1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("type C:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("valueC number(1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("func testAlias:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("a A (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("b B (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("c C (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("alias Alias1:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("a->valueA");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("alias Alias2:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("b->valueB");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set c->valueC:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Alias1*Alias2");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def testAlias(a: A, b: B) -> C:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("a : A");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("b : B");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("c : C");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Alias1 = rosetta_resolve_attr(rosetta_resolve_attr(self, \"a\"), \"valueA\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Alias2 = rosetta_resolve_attr(rosetta_resolve_attr(self, \"b\"), \"valueB\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("c = _get_rosetta_object(\'C\', \'valueC\', (rosetta_resolve_attr(self, \"Alias1\") * rosetta_resolve_attr(self, \"Alias2\")))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return c");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testComplexSetConstructors() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("type InterestRatePayout: <\" A class to specify all of the terms necessary to define and calculate a cash flow based on a fixed, a floating or an inflation index rate. The interest rate payout can be applied to interest rate swaps and FRA (which both have two associated interest rate payouts), credit default swaps (to represent the fee leg when subject to periodic payments) and equity swaps (to represent the funding leg). The associated globalKey denotes the ability to associate a hash value to the InterestRatePayout instantiations for the purpose of model cross-referencing, in support of functionality such as the event effect and the lineage.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[metadata key]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("rateSpecification RateSpecification (0..1) <\"The specification of the rate value(s) applicable to the contract using either a floating rate calculation, a single fixed rate, a fixed rate schedule, or an inflation rate calculation.\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("type RateSpecification: <\" A class to specify the fixed interest rate, floating interest rate or inflation rate.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("floatingRate FloatingRateSpecification (0..1) <\"The floating interest rate specification, which includes the definition of the floating rate index. the tenor, the initial value, and, when applicable, the spread, the rounding convention, the averaging method and the negative interest rate treatment.\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("type FloatingRateSpecification: <\"A class defining a floating interest rate through the specification of the floating rate index, the tenor, the multiplier schedule, the spread, the qualification of whether a specific rate treatment and/or a cap or floor apply.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[metadata key]");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("rateOption FloatingRateOption (0..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("type FloatingRateOption: <\"Specification of a floating rate option as a floating rate index and tenor.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("value int(1..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("type ObservationIdentifier: <\"Defines the parameters needed to uniquely identify a piece of data among the population of all available market data.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("observable Observable (1..1) <\"Represents the asset or rate to which the observation relates.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("observationDate date (1..1) <\"Specifies the date value to use when resolving the market data.\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("type Observable: <\"Specifies the object to be observed for a price, it could be an asset or a reference.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[metadata key]");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("rateOption FloatingRateOption (0..1) <\"Specifies a floating rate index and tenor.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("func ResolveInterestRateObservationIdentifiers: <\"Defines which attributes on the InterestRatePayout should be used to locate and resolve the underlier\'s price, for example for the reset process.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("payout InterestRatePayout (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("date date (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("identifiers ObservationIdentifier (1..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set identifiers -> observable -> rateOption:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("payout -> rateSpecification -> floatingRate -> rateOption");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("set identifiers -> observationDate:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("date");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def ResolveInterestRateObservationIdentifiers(payout: InterestRatePayout, date: datetime.date) -> ObservationIdentifier:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Defines which attributes on the InterestRatePayout should be used to locate and resolve the underlier\'s price, for example for the reset process.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("payout : InterestRatePayout");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("date : date");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("identifiers : ObservationIdentifier");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("identifiers = _get_rosetta_object(\'ObservationIdentifier\', \'observable\', _get_rosetta_object(\'Observable\', \'rateOption\', rosetta_resolve_attr(rosetta_resolve_attr(rosetta_resolve_attr(rosetta_resolve_attr(self, \"payout\"), \"rateSpecification\"), \"floatingRate\"), \"rateOption\")))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("identifiers = set_rosetta_attr(rosetta_resolve_attr(self, \'identifiers\'), \'observationDate\', rosetta_resolve_attr(self, \"date\"))");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return identifiers");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testCondition() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func RoundToNearest:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("value number (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("nearest number (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("roundingMode RoundingModeEnum (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("roundedValue number (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("condition PositiveNearest:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("nearest > 0");
    _builder.newLine();
    _builder.append("enum RoundingModeEnum:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Down");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Up");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def RoundToNearest(value: Decimal, nearest: Decimal, roundingMode: RoundingModeEnum) -> Decimal:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("value : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("nearest : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("roundingMode : RoundingModeEnum");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("roundedValue : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("_pre_registry = {}");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("@rosetta_local_condition(_pre_registry)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def condition_0_PositiveNearest(self):");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return all_elements(rosetta_resolve_attr(self, \"nearest\"), \">\", 0)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# Execute all registered conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("execute_local_conditions(_pre_registry, \'Pre-condition\')");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("roundedValue = rosetta_resolve_attr(self, \"roundedValue\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return roundedValue");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testMultipleConditions() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func RoundToNearest:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("value number (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("nearest number (1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("roundingMode RoundingModeEnum (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("roundedValue number (1..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("condition PositiveNearest:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("nearest > 0");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("condition valueNegative:");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("value < 0");
    _builder.newLine();
    _builder.append("enum RoundingModeEnum:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Down");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Up");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def RoundToNearest(value: Decimal, nearest: Decimal, roundingMode: RoundingModeEnum) -> Decimal:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("value : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("nearest : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("roundingMode : RoundingModeEnum");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("roundedValue : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("_pre_registry = {}");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("@rosetta_local_condition(_pre_registry)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def condition_0_PositiveNearest(self):");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return all_elements(rosetta_resolve_attr(self, \"nearest\"), \">\", 0)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("@rosetta_local_condition(_pre_registry)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def condition_1_valueNegative(self):");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return all_elements(rosetta_resolve_attr(self, \"value\"), \"<\", 0)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# Execute all registered conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("execute_local_conditions(_pre_registry, \'Pre-condition\')");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("roundedValue = rosetta_resolve_attr(self, \"roundedValue\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return roundedValue");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void testPostCondition() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("func NewFloatingPayout: <\"Function specification to create the interest rate (floating) payout part of an Equity Swap according to the 2018 ISDA CDM Equity Confirmation template.\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("inputs: masterConfirmation EquitySwapMasterConfirmation2018 (0..1)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("output: interestRatePayout InterestRatePayout (1..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("post-condition InterestRatePayoutTerms: <\"Interest rate payout must inherit terms from the Master Confirmation Agreement when it exists.\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if masterConfirmation exists then ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("//interestRatePayout -> calculationPeriodDates = masterConfirmation -> equityCalculationPeriod and ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("interestRatePayout -> paymentDates = masterConfirmation -> equityCashSettlementDates");
    _builder.newLine();
    _builder.append("type EquitySwapMasterConfirmation2018:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("equityCashSettlementDates PaymentDates (1..1) ");
    _builder.newLine();
    _builder.append("type PaymentDates:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("date date(0..1)");
    _builder.newLine();
    _builder.append("type InterestRatePayout:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("paymentDates PaymentDates(0..1)");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def NewFloatingPayout(masterConfirmation: EquitySwapMasterConfirmation2018 | None) -> InterestRatePayout:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Function specification to create the interest rate (floating) payout part of an Equity Swap according to the 2018 ISDA CDM Equity Confirmation template.");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("masterConfirmation : EquitySwapMasterConfirmation2018");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("interestRatePayout : InterestRatePayout");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("_post_registry = {}");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("interestRatePayout = rosetta_resolve_attr(self, \"interestRatePayout\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# post-conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("@rosetta_local_condition(_post_registry)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("def condition_0_InterestRatePayoutTerms(self):");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("Interest rate payout must inherit terms from the Master Confirmation Agreement when it exists.");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("def _then_fn0():");
    _builder_1.newLine();
    _builder_1.append("            ");
    _builder_1.append("return all_elements(rosetta_resolve_attr(rosetta_resolve_attr(self, \"interestRatePayout\"), \"paymentDates\"), \"=\", rosetta_resolve_attr(rosetta_resolve_attr(self, \"masterConfirmation\"), \"equityCashSettlementDates\"))");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("def _else_fn0():");
    _builder_1.newLine();
    _builder_1.append("            ");
    _builder_1.append("return True");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("return if_cond_fn(rosetta_attr_exists(rosetta_resolve_attr(self, \"masterConfirmation\")), _then_fn0, _else_fn0)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("# Execute all registered post-conditions");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("execute_local_conditions(_post_registry, \'Post-condition\')");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return interestRatePayout");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("sys.modules[__name__].__class__ = create_module_attr_guardian(sys.modules[__name__].__class__)");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  @Test
  public void functionCallTest() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("type InterestRatePayout: <\" A class to specify all of the terms necessary to define and calculate a cash flow based on a fixed, a floating or an inflation index rate. The interest rate payout can be applied to interest rate swaps and FRA (which both have two associated interest rate payouts), credit default swaps (to represent the fee leg when subject to periodic payments) and equity swaps (to represent the funding leg). The associated globalKey denotes the ability to associate a hash value to the InterestRatePayout instantiations for the purpose of model cross-referencing, in support of functionality such as the event effect and the lineage.\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("[metadata key]");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("rateSpecification RateSpecification (0..1) <\"The specification of the rate value(s) applicable to the contract using either a floating rate calculation, a single fixed rate, a fixed rate schedule, or an inflation rate calculation.\">");
    _builder.newLine();
    _builder.append("                ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("type RateSpecification: <\" A class to specify the fixed interest rate, floating interest rate or inflation rate.\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("floatingRate FloatingRateSpecification (0..1) <\"The floating interest rate specification, which includes the definition of the floating rate index. the tenor, the initial value, and, when applicable, the spread, the rounding convention, the averaging method and the negative interest rate treatment.\">");
    _builder.newLine();
    _builder.append("                ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("type FloatingRateSpecification: <\"A class defining a floating interest rate through the specification of the floating rate index, the tenor, the multiplier schedule, the spread, the qualification of whether a specific rate treatment and/or a cap or floor apply.\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("[metadata key]");
    _builder.newLine();
    _builder.append("                ");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("rateOption FloatingRateOption (0..1)");
    _builder.newLine();
    _builder.append("                ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("type FloatingRateOption: <\"Specification of a floating rate option as a floating rate index and tenor.\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("value int(1..1)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("func FixedAmount:");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("[calculation]");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("interestRatePayout InterestRatePayout (1..1)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("date date (1..1)");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("fixedAmount number (1..1)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("          ");
    _builder.append("alias dayCountFraction: DayCountFraction(interestRatePayout, date)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("func DayCountFraction:");
    _builder.newLine();
    _builder.append("             ");
    _builder.append("inputs:");
    _builder.newLine();
    _builder.append("                 ");
    _builder.append("interestRatePayout InterestRatePayout (1..1)");
    _builder.newLine();
    _builder.append("                 ");
    _builder.append("date date(1..1)");
    _builder.newLine();
    _builder.append("             ");
    _builder.append("output:");
    _builder.newLine();
    _builder.append("                 ");
    _builder.append("a number(1..1)");
    _builder.newLine();
    final HashMap<String, CharSequence> python = this.generatePython(_builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("@replaceable");
    _builder_1.newLine();
    _builder_1.append("def DayCountFraction(interestRatePayout: InterestRatePayout, date: datetime.date) -> Decimal:");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Parameters ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("----------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("interestRatePayout : InterestRatePayout");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("date : date");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Returns");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("-------");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("a : number");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("\"\"\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("self = inspect.currentframe()");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("a = rosetta_resolve_attr(self, \"a\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return a");
    _builder_1.newLine();
    final String expected = _builder_1.toString();
    Assertions.assertTrue(python.toString().contains(expected));
  }

  public HashMap<String, CharSequence> generatePython(final CharSequence model) {
    HashMap<String, CharSequence> _xblockexpression = null;
    {
      final RosettaModel m = this._modelHelper.parseRosetta(model);
      final ResourceSet resourceSet = m.eResource().getResourceSet();
      final String version = m.getVersion();
      final HashMap<String, CharSequence> result = CollectionLiterals.<String, CharSequence>newHashMap();
      result.putAll(this.generator.beforeAllGenerate(resourceSet, Collections.<RosettaModel>unmodifiableSet(CollectionLiterals.<RosettaModel>newHashSet(m)), version));
      result.putAll(this.generator.beforeGenerate(m.eResource(), m, version));
      result.putAll(this.generator.generate(m.eResource(), m, version));
      result.putAll(this.generator.afterGenerate(m.eResource(), m, version));
      result.putAll(this.generator.afterAllGenerate(resourceSet, Collections.<RosettaModel>unmodifiableSet(CollectionLiterals.<RosettaModel>newHashSet(m)), version));
      _xblockexpression = result;
    }
    return _xblockexpression;
  }
}
